{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-debug.aar",
          "url": "webview_flutter_android-1.0-debug.aar",
          "size": 113881,
          "sha512": "a2abb89df1979f301c58f3b0a652b6e73bd38108d2c7b6a9012a890642ca7af11f4b2dc7def8b618456869a697f8e617e0305e548d38930fd703bcb7f2a7665c",
          "sha256": "b9c6e4ef7c76588df13610ccf93168475d008fc6ed90326dfe57d59104baff8b",
          "sha1": "ef544820825f47429c0f60c1cc5bb2275c08ce59",
          "md5": "14da99d52ae08931ae89732d1a42a0c4"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-debug.aar",
          "url": "webview_flutter_android-1.0-debug.aar",
          "size": 113881,
          "sha512": "a2abb89df1979f301c58f3b0a652b6e73bd38108d2c7b6a9012a890642ca7af11f4b2dc7def8b618456869a697f8e617e0305e548d38930fd703bcb7f2a7665c",
          "sha256": "b9c6e4ef7c76588df13610ccf93168475d008fc6ed90326dfe57d59104baff8b",
          "sha1": "ef544820825f47429c0f60c1cc5bb2275c08ce59",
          "md5": "14da99d52ae08931ae89732d1a42a0c4"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-release.aar",
          "url": "webview_flutter_android-1.0-release.aar",
          "size": 107413,
          "sha512": "e6ad76ae2d860c446f3eea62292cb34ed48a707d6eb5b4bbb78cd13bb7de3ba91fb8a366101e75b41f95b26d3eb5abe40b8ce476695101e356e363ced568e461",
          "sha256": "edaf04b9d700638d0d06134fdb3d69cd1a657f58d2e86ebf537d7624a8348933",
          "sha1": "182dfd956ec9383c979e0f98db5838088bf75e39",
          "md5": "884b1ab03ccfafac409f491184084ca9"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-release.aar",
          "url": "webview_flutter_android-1.0-release.aar",
          "size": 107413,
          "sha512": "e6ad76ae2d860c446f3eea62292cb34ed48a707d6eb5b4bbb78cd13bb7de3ba91fb8a366101e75b41f95b26d3eb5abe40b8ce476695101e356e363ced568e461",
          "sha256": "edaf04b9d700638d0d06134fdb3d69cd1a657f58d2e86ebf537d7624a8348933",
          "sha1": "182dfd956ec9383c979e0f98db5838088bf75e39",
          "md5": "884b1ab03ccfafac409f491184084ca9"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-profile.aar",
          "url": "webview_flutter_android-1.0-profile.aar",
          "size": 107415,
          "sha512": "3bd8290e0869418c29026a50bf7215633c892cde81e5aef40b0522c7cf9b4ab11df24197234c4d0b4f7bd6acdc932f78a18d487ceed575c89b715006a9122d11",
          "sha256": "a8fdf969f71349156a70f39975a12d95ab155a43df8ac90832b4a88e6d23a275",
          "sha1": "1e0616071ecf26223c942bcb78927665f3231cc5",
          "md5": "e272938174caa65ffda02cbf0c1df903"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android-1.0-profile.aar",
          "url": "webview_flutter_android-1.0-profile.aar",
          "size": 107415,
          "sha512": "3bd8290e0869418c29026a50bf7215633c892cde81e5aef40b0522c7cf9b4ab11df24197234c4d0b4f7bd6acdc932f78a18d487ceed575c89b715006a9122d11",
          "sha256": "a8fdf969f71349156a70f39975a12d95ab155a43df8ac90832b4a88e6d23a275",
          "sha1": "1e0616071ecf26223c942bcb78927665f3231cc5",
          "md5": "e272938174caa65ffda02cbf0c1df903"
        }
      ]
    }
  ]
}
