{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_file",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "open_file-1.1.2-debug.aar",
          "url": "open_file-1.1.2-debug.aar",
          "size": 13838,
          "sha512": "66fb93a93565ce6eb58d8c9d9a7be38dffbf06fa49167660b1b14778805318460e357b4ff199b3a1df20e443418e2b318671473b35b6a657156db6675d564699",
          "sha256": "eb9b2c773c9f6de4b8dafa9be7fddfd7429f8d1fb0e9e257ae0fb54e2aee3cb4",
          "sha1": "2b9da2e968aa55bfea46bccbda541a535ede90c1",
          "md5": "de9122e8c5b5acb714179c74fbe33ba8"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file-1.1.2-debug.aar",
          "url": "open_file-1.1.2-debug.aar",
          "size": 13838,
          "sha512": "66fb93a93565ce6eb58d8c9d9a7be38dffbf06fa49167660b1b14778805318460e357b4ff199b3a1df20e443418e2b318671473b35b6a657156db6675d564699",
          "sha256": "eb9b2c773c9f6de4b8dafa9be7fddfd7429f8d1fb0e9e257ae0fb54e2aee3cb4",
          "sha1": "2b9da2e968aa55bfea46bccbda541a535ede90c1",
          "md5": "de9122e8c5b5acb714179c74fbe33ba8"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "open_file-1.1.2-release.aar",
          "url": "open_file-1.1.2-release.aar",
          "size": 13292,
          "sha512": "c44bf9125bba14804a6befb93126ecc3452cc1de3e214cf0f67b8990a137f179b24e31c891ab0e7a51ffec7adddab5be27a3117eddef69413ad7e3d7c892c603",
          "sha256": "43ff5e68774f4c912264d6ee8d247e24d10238c1d504913c19f0fbedf0b3311a",
          "sha1": "1d1071ec62a930b7471918a2b5ee2ab0fc7796d1",
          "md5": "07421763b2bd2b423fba04f62fbccf12"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file-1.1.2-release.aar",
          "url": "open_file-1.1.2-release.aar",
          "size": 13292,
          "sha512": "c44bf9125bba14804a6befb93126ecc3452cc1de3e214cf0f67b8990a137f179b24e31c891ab0e7a51ffec7adddab5be27a3117eddef69413ad7e3d7c892c603",
          "sha256": "43ff5e68774f4c912264d6ee8d247e24d10238c1d504913c19f0fbedf0b3311a",
          "sha1": "1d1071ec62a930b7471918a2b5ee2ab0fc7796d1",
          "md5": "07421763b2bd2b423fba04f62fbccf12"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "open_file-1.1.2-profile.aar",
          "url": "open_file-1.1.2-profile.aar",
          "size": 13292,
          "sha512": "000ccc3fd1f2e3390c7720fdf5c79e134269873912cd01dea80933aa8eae24a60a539779f0ea62e1fdcd9bd81f3fa066352b6f6a3dcaf151b30a206fb8ca85df",
          "sha256": "ae842ac9eca2b2f3047e3a177f61b4db83c823610861082340844b5cf0802979",
          "sha1": "1a75c56c51009d8c7289f04fe707c2ff147b4ebc",
          "md5": "089112043f2bbc5704a20f10595799b9"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file-1.1.2-profile.aar",
          "url": "open_file-1.1.2-profile.aar",
          "size": 13292,
          "sha512": "000ccc3fd1f2e3390c7720fdf5c79e134269873912cd01dea80933aa8eae24a60a539779f0ea62e1fdcd9bd81f3fa066352b6f6a3dcaf151b30a206fb8ca85df",
          "sha256": "ae842ac9eca2b2f3047e3a177f61b4db83c823610861082340844b5cf0802979",
          "sha1": "1a75c56c51009d8c7289f04fe707c2ff147b4ebc",
          "md5": "089112043f2bbc5704a20f10595799b9"
        }
      ]
    }
  ]
}
