{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.network_info",
    "module": "network_info_plus_debug",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus_debug-1.1.0.aar",
          "url": "network_info_plus_debug-1.1.0.aar",
          "size": 12124,
          "sha512": "79349856e1b1210ac258a0f57684a4d2fb67fb41988b87ec7f9186a1745c7ea2fb77948c5ca9e43c466d81fe0b05a8932c27655ed4082e41b4198368f27e450c",
          "sha256": "a21dc773a1aa361c1833d9ba633ed40d625d5f25d988cf31215f33db49434353",
          "sha1": "910b35ef47e5cb4bff7fd7a1a07f92b8f3a8e537",
          "md5": "9dad39440b25a83dd49dc76b2a777132"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus_debug-1.1.0.aar",
          "url": "network_info_plus_debug-1.1.0.aar",
          "size": 12124,
          "sha512": "79349856e1b1210ac258a0f57684a4d2fb67fb41988b87ec7f9186a1745c7ea2fb77948c5ca9e43c466d81fe0b05a8932c27655ed4082e41b4198368f27e450c",
          "sha256": "a21dc773a1aa361c1833d9ba633ed40d625d5f25d988cf31215f33db49434353",
          "sha1": "910b35ef47e5cb4bff7fd7a1a07f92b8f3a8e537",
          "md5": "9dad39440b25a83dd49dc76b2a777132"
        }
      ]
    }
  ]
}
