{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jointelli.cpe_module",
    "module": "flutter",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.network_info",
          "module": "network_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.wifi_info_flutter",
          "module": "wifi_info_flutter",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_file",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.1.3-debug.aar",
          "url": "flutter-1.1.3-debug.aar",
          "size": 18246560,
          "sha512": "4deaf04ab8241a9edbf6a09fb4419668dbb2fd044887a3460d475edef831a3cfece849da9b6f8efee320bda26b8b8ecde44989ecf28785121142c49cead5f80b",
          "sha256": "3e463e7a9349b120e3188dd5b722b22d253b3577e235c1c9f401c03491b90c8a",
          "sha1": "657293416580c5348f1527cebc8ebb10f990a4e2",
          "md5": "f87cb5eba009b2ab9df1bdf31b69c570"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.network_info",
          "module": "network_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.wifi_info_flutter",
          "module": "wifi_info_flutter",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_file",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.1.3-debug.aar",
          "url": "flutter-1.1.3-debug.aar",
          "size": 18246560,
          "sha512": "4deaf04ab8241a9edbf6a09fb4419668dbb2fd044887a3460d475edef831a3cfece849da9b6f8efee320bda26b8b8ecde44989ecf28785121142c49cead5f80b",
          "sha256": "3e463e7a9349b120e3188dd5b722b22d253b3577e235c1c9f401c03491b90c8a",
          "sha1": "657293416580c5348f1527cebc8ebb10f990a4e2",
          "md5": "f87cb5eba009b2ab9df1bdf31b69c570"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.network_info",
          "module": "network_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.wifi_info_flutter",
          "module": "wifi_info_flutter",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_file",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.1.3-release.aar",
          "url": "flutter-1.1.3-release.aar",
          "size": 9374995,
          "sha512": "c970645b1980bc747b879f31dd721d7b693afd5d9225ea4a4f96edda84824070689ff08518e381dd0a061812995d8fd010318c6b1d18bae80fae5e6de9dfe96f",
          "sha256": "a7052858c2d1f55edc9821c3006453f9d22ebf6cadcf8b904cd7fb7691e165ec",
          "sha1": "e0946b1351f2204d6b143e967fb10977e364e44a",
          "md5": "c8a908405481cb1b22999393e8a50940"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.network_info",
          "module": "network_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.wifi_info_flutter",
          "module": "wifi_info_flutter",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_file",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.1.3-release.aar",
          "url": "flutter-1.1.3-release.aar",
          "size": 9374995,
          "sha512": "c970645b1980bc747b879f31dd721d7b693afd5d9225ea4a4f96edda84824070689ff08518e381dd0a061812995d8fd010318c6b1d18bae80fae5e6de9dfe96f",
          "sha256": "a7052858c2d1f55edc9821c3006453f9d22ebf6cadcf8b904cd7fb7691e165ec",
          "sha1": "e0946b1351f2204d6b143e967fb10977e364e44a",
          "md5": "c8a908405481cb1b22999393e8a50940"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.network_info",
          "module": "network_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.wifi_info_flutter",
          "module": "wifi_info_flutter",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_file",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.1.3-profile.aar",
          "url": "flutter-1.1.3-profile.aar",
          "size": 474708,
          "sha512": "9ff69e791db6da3a743cb62a49b55ed7c8f687777f24a09e3acaac2d9cfe56aaa48c09adee4169e31df1b1626f5f53fa0d1c63c6b2460b1311c838152a0c59ae",
          "sha256": "b957bc397f1dd210a85f247f35ab67a7487ad2b7c888bbf123276c72672a02ae",
          "sha1": "d66a1194085e6c89eb45113e075d30f80a2f01cf",
          "md5": "7c469a6a302cc4a327c7cd98e283fead"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.network_info",
          "module": "network_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.wifi_info_flutter",
          "module": "wifi_info_flutter",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_file",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.1.3-profile.aar",
          "url": "flutter-1.1.3-profile.aar",
          "size": 474708,
          "sha512": "9ff69e791db6da3a743cb62a49b55ed7c8f687777f24a09e3acaac2d9cfe56aaa48c09adee4169e31df1b1626f5f53fa0d1c63c6b2460b1311c838152a0c59ae",
          "sha256": "b957bc397f1dd210a85f247f35ab67a7487ad2b7c888bbf123276c72672a02ae",
          "sha1": "d66a1194085e6c89eb45113e075d30f80a2f01cf",
          "md5": "7c469a6a302cc4a327c7cd98e283fead"
        }
      ]
    }
  ]
}
