{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_debug-1.0.aar",
          "url": "connectivity_debug-1.0.aar",
          "size": 9388,
          "sha512": "4e851fa4ec2d1cf99d036defe79397e8d5f4d61e61bca5d6f8884e8a730f803ba9afaba1b5c547c12970a1b8bd3dea22f6a608e3b39ea79abb8e398e55eae8ed",
          "sha256": "82588692ae7ece9c867b3e4b129938d2da27bb1c4639b701b66808aaccaad5ca",
          "sha1": "55f638bed478361bf8540459173f1358716b7bdf",
          "md5": "515e0fbca7009cd8c746ca0c05d93cf2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_debug-1.0.aar",
          "url": "connectivity_debug-1.0.aar",
          "size": 9388,
          "sha512": "4e851fa4ec2d1cf99d036defe79397e8d5f4d61e61bca5d6f8884e8a730f803ba9afaba1b5c547c12970a1b8bd3dea22f6a608e3b39ea79abb8e398e55eae8ed",
          "sha256": "82588692ae7ece9c867b3e4b129938d2da27bb1c4639b701b66808aaccaad5ca",
          "sha1": "55f638bed478361bf8540459173f1358716b7bdf",
          "md5": "515e0fbca7009cd8c746ca0c05d93cf2"
        }
      ]
    }
  ]
}
