{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity_release",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_release-1.1.0.aar",
          "url": "connectivity_release-1.1.0.aar",
          "size": 9021,
          "sha512": "c082e60e1b3745b31e16a21819f6b413b921d569d5e4569cb8770ba9f936ad55a2b9e255a840c63db2693323b89e798386b0cc256a6ace22d020c8b50f9c86f9",
          "sha256": "73084c2fdf17584c7da34920d8549ec51bb4d1aa34ad24fe0cb7c830231f7ea9",
          "sha1": "1beb7ade83a982f79b3618f463b2509c62564b69",
          "md5": "cf22aae284aca9ee23331fd83b94dff7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_release-1.1.0.aar",
          "url": "connectivity_release-1.1.0.aar",
          "size": 9021,
          "sha512": "c082e60e1b3745b31e16a21819f6b413b921d569d5e4569cb8770ba9f936ad55a2b9e255a840c63db2693323b89e798386b0cc256a6ace22d020c8b50f9c86f9",
          "sha256": "73084c2fdf17584c7da34920d8549ec51bb4d1aa34ad24fe0cb7c830231f7ea9",
          "sha1": "1beb7ade83a982f79b3618f463b2509c62564b69",
          "md5": "cf22aae284aca9ee23331fd83b94dff7"
        }
      ]
    }
  ]
}
