{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jointelli.cpe_module",
    "module": "flutter_release",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.network_info",
          "module": "network_info_plus",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.wifi_info_flutter",
          "module": "wifi_info_flutter",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_file",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.1.1.aar",
          "url": "flutter_release-1.1.1.aar",
          "size": 9374247,
          "sha512": "aad7c9110a7a0fdbdb0d8f88f57e05544c476652012057dd2abf676d5ed04f7a820ba061ffe22c17d0c0dab11957d59bcb372ff977eddcbbe531257fff840dad",
          "sha256": "842b3e4ee57e86bc272fdf42c4333596844a795c5a2b6d68986a6f9820b28cf0",
          "sha1": "2a8bdaa3be4ef16ca7512034bddbb80249b2e419",
          "md5": "4226b9d7637bcaa7a0e5f13cdf222338"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.network_info",
          "module": "network_info_plus",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.example.appsettings",
          "module": "app_settings",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.wifi_info_flutter",
          "module": "wifi_info_flutter",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.connectivity",
          "module": "connectivity",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_file",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.1.1.aar",
          "url": "flutter_release-1.1.1.aar",
          "size": 9374247,
          "sha512": "aad7c9110a7a0fdbdb0d8f88f57e05544c476652012057dd2abf676d5ed04f7a820ba061ffe22c17d0c0dab11957d59bcb372ff977eddcbbe531257fff840dad",
          "sha256": "842b3e4ee57e86bc272fdf42c4333596844a795c5a2b6d68986a6f9820b28cf0",
          "sha1": "2a8bdaa3be4ef16ca7512034bddbb80249b2e419",
          "md5": "4226b9d7637bcaa7a0e5f13cdf222338"
        }
      ]
    }
  ]
}
