{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.wifi_info_flutter",
    "module": "wifi_info_flutter",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_info_flutter-1.1.0-debug.aar",
          "url": "wifi_info_flutter-1.1.0-debug.aar",
          "size": 7821,
          "sha512": "fe99c926a550e3c3d223e4137c11fae9130833dd82780053d79f3b2118dca910bbbaa4b0067848e45cbf2bc880ce3271ff4699f181f87074af69353936d3ae9c",
          "sha256": "772297fc670b8b9906e64aecb26a9054c3d52da6a8a81450a2079e354459e1e3",
          "sha1": "4c40aa1eb2063ab442d5ecbf8470514522f31d1a",
          "md5": "627a8dd66717828840ca9477e4360612"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_info_flutter-1.1.0-debug.aar",
          "url": "wifi_info_flutter-1.1.0-debug.aar",
          "size": 7821,
          "sha512": "fe99c926a550e3c3d223e4137c11fae9130833dd82780053d79f3b2118dca910bbbaa4b0067848e45cbf2bc880ce3271ff4699f181f87074af69353936d3ae9c",
          "sha256": "772297fc670b8b9906e64aecb26a9054c3d52da6a8a81450a2079e354459e1e3",
          "sha1": "4c40aa1eb2063ab442d5ecbf8470514522f31d1a",
          "md5": "627a8dd66717828840ca9477e4360612"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_info_flutter-1.1.0-release.aar",
          "url": "wifi_info_flutter-1.1.0-release.aar",
          "size": 7516,
          "sha512": "aa712619bdb878c6a326254d35900373b2e2333bbda0a2521cccea08f77f940ffe975fbe8a04af2e564902c489920e58507e4bc664db9dbf137c44c6c2b1972d",
          "sha256": "5ef810e5bb5dead1aff1697069c9658609f838ca0933a36af1c2ada5d6bad043",
          "sha1": "b52db612cc9176532be7cd5a10101af505e4d98c",
          "md5": "d60c8a6b0fc519435fe78fc7550b09eb"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_info_flutter-1.1.0-release.aar",
          "url": "wifi_info_flutter-1.1.0-release.aar",
          "size": 7516,
          "sha512": "aa712619bdb878c6a326254d35900373b2e2333bbda0a2521cccea08f77f940ffe975fbe8a04af2e564902c489920e58507e4bc664db9dbf137c44c6c2b1972d",
          "sha256": "5ef810e5bb5dead1aff1697069c9658609f838ca0933a36af1c2ada5d6bad043",
          "sha1": "b52db612cc9176532be7cd5a10101af505e4d98c",
          "md5": "d60c8a6b0fc519435fe78fc7550b09eb"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_info_flutter-1.1.0-profile.aar",
          "url": "wifi_info_flutter-1.1.0-profile.aar",
          "size": 7517,
          "sha512": "baca29eb58190583e33f0507c0574759633fa66bae6b0f5049f76a163ac9553b254ddb2a91846687a0db48c0775c4ba4078e027e6523972300709e568d0b2048",
          "sha256": "426a297ee77c9462f7d03a9af6dabbb14f2bbba3a3c80d03a62b2087a3c3a556",
          "sha1": "284ed0d2780ebba7b35ea5f79414ced7eba688fc",
          "md5": "081a9ae0de20fb69630568e381fcc96f"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_info_flutter-1.1.0-profile.aar",
          "url": "wifi_info_flutter-1.1.0-profile.aar",
          "size": 7517,
          "sha512": "baca29eb58190583e33f0507c0574759633fa66bae6b0f5049f76a163ac9553b254ddb2a91846687a0db48c0775c4ba4078e027e6523972300709e568d0b2048",
          "sha256": "426a297ee77c9462f7d03a9af6dabbb14f2bbba3a3c80d03a62b2087a3c3a556",
          "sha1": "284ed0d2780ebba7b35ea5f79414ced7eba688fc",
          "md5": "081a9ae0de20fb69630568e381fcc96f"
        }
      ]
    }
  ]
}
