{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info-1.1.3-debug.aar",
          "url": "package_info-1.1.3-debug.aar",
          "size": 5263,
          "sha512": "a9b612a1e01c3a932c67b2a250a6533f3ad7fddd3cd2415262208992ad246ac8b9f197b3590fb6b3ad7a32781b486f19669f3e280a167f43f2cbbb47bbae622b",
          "sha256": "f0a0bfd442cd38e4ad28708e1081080ab5a137292acc1ad5de3d168472f79df0",
          "sha1": "60f037dc81d091143e20eea6ac168671708c38dd",
          "md5": "094f878647c6f26ec0444c9919ba52fe"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info-1.1.3-debug.aar",
          "url": "package_info-1.1.3-debug.aar",
          "size": 5263,
          "sha512": "a9b612a1e01c3a932c67b2a250a6533f3ad7fddd3cd2415262208992ad246ac8b9f197b3590fb6b3ad7a32781b486f19669f3e280a167f43f2cbbb47bbae622b",
          "sha256": "f0a0bfd442cd38e4ad28708e1081080ab5a137292acc1ad5de3d168472f79df0",
          "sha1": "60f037dc81d091143e20eea6ac168671708c38dd",
          "md5": "094f878647c6f26ec0444c9919ba52fe"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info-1.1.3-release.aar",
          "url": "package_info-1.1.3-release.aar",
          "size": 5032,
          "sha512": "2d057f3e70b7a2ab79d037a88596e13fec4ea3aa26f3349048acc46bcbaa7374923c118818b7957684cfb6dcff1e04b95058d0f71dd67ec524a82a4559530346",
          "sha256": "c55591072be92133a51c3f279011295cadcb137b8ded97cb9bf4286ea8663c75",
          "sha1": "e62e6f4132329e191e9a1dfe1665b28596ac98b9",
          "md5": "f6a474b5fe734007c3b93d76d20a2a0e"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info-1.1.3-release.aar",
          "url": "package_info-1.1.3-release.aar",
          "size": 5032,
          "sha512": "2d057f3e70b7a2ab79d037a88596e13fec4ea3aa26f3349048acc46bcbaa7374923c118818b7957684cfb6dcff1e04b95058d0f71dd67ec524a82a4559530346",
          "sha256": "c55591072be92133a51c3f279011295cadcb137b8ded97cb9bf4286ea8663c75",
          "sha1": "e62e6f4132329e191e9a1dfe1665b28596ac98b9",
          "md5": "f6a474b5fe734007c3b93d76d20a2a0e"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info-1.1.3-profile.aar",
          "url": "package_info-1.1.3-profile.aar",
          "size": 5036,
          "sha512": "a49974726755ad2aeec47673c01a7fc262fbf8ee423dc24e99614a1645733e382b229d529cebb446b640792e48376d57781ae1511cdedcf381bc669b45a70099",
          "sha256": "af0033b90780c2ea82348bbdb68ed3cc9b2d7d7d11a90f300c5a9b6ccd2395d1",
          "sha1": "b31e231b8420329e7140d2c2f4770584adc3a444",
          "md5": "f51470d7be868dc372b5c004c6aa6cfa"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info-1.1.3-profile.aar",
          "url": "package_info-1.1.3-profile.aar",
          "size": 5036,
          "sha512": "a49974726755ad2aeec47673c01a7fc262fbf8ee423dc24e99614a1645733e382b229d529cebb446b640792e48376d57781ae1511cdedcf381bc669b45a70099",
          "sha256": "af0033b90780c2ea82348bbdb68ed3cc9b2d7d7d11a90f300c5a9b6ccd2395d1",
          "sha1": "b31e231b8420329e7140d2c2f4770584adc3a444",
          "md5": "f51470d7be868dc372b5c004c6aa6cfa"
        }
      ]
    }
  ]
}
