{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_profile",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_profile-1.1.0.aar",
          "url": "package_info_profile-1.1.0.aar",
          "size": 5036,
          "sha512": "a49974726755ad2aeec47673c01a7fc262fbf8ee423dc24e99614a1645733e382b229d529cebb446b640792e48376d57781ae1511cdedcf381bc669b45a70099",
          "sha256": "af0033b90780c2ea82348bbdb68ed3cc9b2d7d7d11a90f300c5a9b6ccd2395d1",
          "sha1": "b31e231b8420329e7140d2c2f4770584adc3a444",
          "md5": "f51470d7be868dc372b5c004c6aa6cfa"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_profile-1.1.0.aar",
          "url": "package_info_profile-1.1.0.aar",
          "size": 5036,
          "sha512": "a49974726755ad2aeec47673c01a7fc262fbf8ee423dc24e99614a1645733e382b229d529cebb446b640792e48376d57781ae1511cdedcf381bc669b45a70099",
          "sha256": "af0033b90780c2ea82348bbdb68ed3cc9b2d7d7d11a90f300c5a9b6ccd2395d1",
          "sha1": "b31e231b8420329e7140d2c2f4770584adc3a444",
          "md5": "f51470d7be868dc372b5c004c6aa6cfa"
        }
      ]
    }
  ]
}
