{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_file_debug",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_debug-1.1.0.aar",
          "url": "open_file_debug-1.1.0.aar",
          "size": 13838,
          "sha512": "66fb93a93565ce6eb58d8c9d9a7be38dffbf06fa49167660b1b14778805318460e357b4ff199b3a1df20e443418e2b318671473b35b6a657156db6675d564699",
          "sha256": "eb9b2c773c9f6de4b8dafa9be7fddfd7429f8d1fb0e9e257ae0fb54e2aee3cb4",
          "sha1": "2b9da2e968aa55bfea46bccbda541a535ede90c1",
          "md5": "de9122e8c5b5acb714179c74fbe33ba8"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_debug-1.1.0.aar",
          "url": "open_file_debug-1.1.0.aar",
          "size": 13838,
          "sha512": "66fb93a93565ce6eb58d8c9d9a7be38dffbf06fa49167660b1b14778805318460e357b4ff199b3a1df20e443418e2b318671473b35b6a657156db6675d564699",
          "sha256": "eb9b2c773c9f6de4b8dafa9be7fddfd7429f8d1fb0e9e257ae0fb54e2aee3cb4",
          "sha1": "2b9da2e968aa55bfea46bccbda541a535ede90c1",
          "md5": "de9122e8c5b5acb714179c74fbe33ba8"
        }
      ]
    }
  ]
}
