{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.wifi_info_flutter",
    "module": "wifi_info_flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_info_flutter_profile-1.0.aar",
          "url": "wifi_info_flutter_profile-1.0.aar",
          "size": 7517,
          "sha512": "baca29eb58190583e33f0507c0574759633fa66bae6b0f5049f76a163ac9553b254ddb2a91846687a0db48c0775c4ba4078e027e6523972300709e568d0b2048",
          "sha256": "426a297ee77c9462f7d03a9af6dabbb14f2bbba3a3c80d03a62b2087a3c3a556",
          "sha1": "284ed0d2780ebba7b35ea5f79414ced7eba688fc",
          "md5": "081a9ae0de20fb69630568e381fcc96f"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_info_flutter_profile-1.0.aar",
          "url": "wifi_info_flutter_profile-1.0.aar",
          "size": 7517,
          "sha512": "baca29eb58190583e33f0507c0574759633fa66bae6b0f5049f76a163ac9553b254ddb2a91846687a0db48c0775c4ba4078e027e6523972300709e568d0b2048",
          "sha256": "426a297ee77c9462f7d03a9af6dabbb14f2bbba3a3c80d03a62b2087a3c3a556",
          "sha1": "284ed0d2780ebba7b35ea5f79414ced7eba688fc",
          "md5": "081a9ae0de20fb69630568e381fcc96f"
        }
      ]
    }
  ]
}
