{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.wifi_info_flutter",
    "module": "wifi_info_flutter_debug",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_info_flutter_debug-1.1.0.aar",
          "url": "wifi_info_flutter_debug-1.1.0.aar",
          "size": 7821,
          "sha512": "fe99c926a550e3c3d223e4137c11fae9130833dd82780053d79f3b2118dca910bbbaa4b0067848e45cbf2bc880ce3271ff4699f181f87074af69353936d3ae9c",
          "sha256": "772297fc670b8b9906e64aecb26a9054c3d52da6a8a81450a2079e354459e1e3",
          "sha1": "4c40aa1eb2063ab442d5ecbf8470514522f31d1a",
          "md5": "627a8dd66717828840ca9477e4360612"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "wifi_info_flutter_debug-1.1.0.aar",
          "url": "wifi_info_flutter_debug-1.1.0.aar",
          "size": 7821,
          "sha512": "fe99c926a550e3c3d223e4137c11fae9130833dd82780053d79f3b2118dca910bbbaa4b0067848e45cbf2bc880ce3271ff4699f181f87074af69353936d3ae9c",
          "sha256": "772297fc670b8b9906e64aecb26a9054c3d52da6a8a81450a2079e354459e1e3",
          "sha1": "4c40aa1eb2063ab442d5ecbf8470514522f31d1a",
          "md5": "627a8dd66717828840ca9477e4360612"
        }
      ]
    }
  ]
}
