{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_release",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_release-1.1.2.aar",
          "url": "package_info_release-1.1.2.aar",
          "size": 5032,
          "sha512": "2d057f3e70b7a2ab79d037a88596e13fec4ea3aa26f3349048acc46bcbaa7374923c118818b7957684cfb6dcff1e04b95058d0f71dd67ec524a82a4559530346",
          "sha256": "c55591072be92133a51c3f279011295cadcb137b8ded97cb9bf4286ea8663c75",
          "sha1": "e62e6f4132329e191e9a1dfe1665b28596ac98b9",
          "md5": "f6a474b5fe734007c3b93d76d20a2a0e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_release-1.1.2.aar",
          "url": "package_info_release-1.1.2.aar",
          "size": 5032,
          "sha512": "2d057f3e70b7a2ab79d037a88596e13fec4ea3aa26f3349048acc46bcbaa7374923c118818b7957684cfb6dcff1e04b95058d0f71dd67ec524a82a4559530346",
          "sha256": "c55591072be92133a51c3f279011295cadcb137b8ded97cb9bf4286ea8663c75",
          "sha1": "e62e6f4132329e191e9a1dfe1665b28596ac98b9",
          "md5": "f6a474b5fe734007c3b93d76d20a2a0e"
        }
      ]
    }
  ]
}
