{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.connectivity",
    "module": "connectivity",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity-1.0-debug.aar",
          "url": "connectivity-1.0-debug.aar",
          "size": 9388,
          "sha512": "4e851fa4ec2d1cf99d036defe79397e8d5f4d61e61bca5d6f8884e8a730f803ba9afaba1b5c547c12970a1b8bd3dea22f6a608e3b39ea79abb8e398e55eae8ed",
          "sha256": "82588692ae7ece9c867b3e4b129938d2da27bb1c4639b701b66808aaccaad5ca",
          "sha1": "55f638bed478361bf8540459173f1358716b7bdf",
          "md5": "515e0fbca7009cd8c746ca0c05d93cf2"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity-1.0-debug.aar",
          "url": "connectivity-1.0-debug.aar",
          "size": 9388,
          "sha512": "4e851fa4ec2d1cf99d036defe79397e8d5f4d61e61bca5d6f8884e8a730f803ba9afaba1b5c547c12970a1b8bd3dea22f6a608e3b39ea79abb8e398e55eae8ed",
          "sha256": "82588692ae7ece9c867b3e4b129938d2da27bb1c4639b701b66808aaccaad5ca",
          "sha1": "55f638bed478361bf8540459173f1358716b7bdf",
          "md5": "515e0fbca7009cd8c746ca0c05d93cf2"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity-1.0-release.aar",
          "url": "connectivity-1.0-release.aar",
          "size": 9021,
          "sha512": "c082e60e1b3745b31e16a21819f6b413b921d569d5e4569cb8770ba9f936ad55a2b9e255a840c63db2693323b89e798386b0cc256a6ace22d020c8b50f9c86f9",
          "sha256": "73084c2fdf17584c7da34920d8549ec51bb4d1aa34ad24fe0cb7c830231f7ea9",
          "sha1": "1beb7ade83a982f79b3618f463b2509c62564b69",
          "md5": "cf22aae284aca9ee23331fd83b94dff7"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity-1.0-release.aar",
          "url": "connectivity-1.0-release.aar",
          "size": 9021,
          "sha512": "c082e60e1b3745b31e16a21819f6b413b921d569d5e4569cb8770ba9f936ad55a2b9e255a840c63db2693323b89e798386b0cc256a6ace22d020c8b50f9c86f9",
          "sha256": "73084c2fdf17584c7da34920d8549ec51bb4d1aa34ad24fe0cb7c830231f7ea9",
          "sha1": "1beb7ade83a982f79b3618f463b2509c62564b69",
          "md5": "cf22aae284aca9ee23331fd83b94dff7"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity-1.0-profile.aar",
          "url": "connectivity-1.0-profile.aar",
          "size": 9020,
          "sha512": "7f65eb1ebf61865dadf2889a24b68709d0d5e91c8b18293e3619cd68e0b9c8be5a5cc9418745f731addbf17a10971c03e533551fb93e0301855e0750b814c78f",
          "sha256": "aa2ebadb88bdbe84236944a6dd746b9117a08b581c6e86dccfbc6ee5cec74ea4",
          "sha1": "448e973af9257b3adf5fecd1c3916138212bf2a3",
          "md5": "265e79c09a48c51eea9966d21dd9b074"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity-1.0-profile.aar",
          "url": "connectivity-1.0-profile.aar",
          "size": 9020,
          "sha512": "7f65eb1ebf61865dadf2889a24b68709d0d5e91c8b18293e3619cd68e0b9c8be5a5cc9418745f731addbf17a10971c03e533551fb93e0301855e0750b814c78f",
          "sha256": "aa2ebadb88bdbe84236944a6dd746b9117a08b581c6e86dccfbc6ee5cec74ea4",
          "sha1": "448e973af9257b3adf5fecd1c3916138212bf2a3",
          "md5": "265e79c09a48c51eea9966d21dd9b074"
        }
      ]
    }
  ]
}
