{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.network_info",
    "module": "network_info_plus_profile",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus_profile-1.1.3.aar",
          "url": "network_info_plus_profile-1.1.3.aar",
          "size": 11700,
          "sha512": "7a7250bf5e549eea324ecd19db789f7dfa16f8a14d77999c0da2b40c984346cb837591256a1386b1be3738f242901f424aaa0646916434e7e926549b2a6fda1c",
          "sha256": "8c967d323c0e8be89ef4e7684bb2cd1a36ebd646a0ecbb0977824b8a8b5c5e50",
          "sha1": "7e0c834080ffa74d3cc94edc06ac2964e5551b23",
          "md5": "aa12001469d157b17af143901162a628"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus_profile-1.1.3.aar",
          "url": "network_info_plus_profile-1.1.3.aar",
          "size": 11700,
          "sha512": "7a7250bf5e549eea324ecd19db789f7dfa16f8a14d77999c0da2b40c984346cb837591256a1386b1be3738f242901f424aaa0646916434e7e926549b2a6fda1c",
          "sha256": "8c967d323c0e8be89ef4e7684bb2cd1a36ebd646a0ecbb0977824b8a8b5c5e50",
          "sha1": "7e0c834080ffa74d3cc94edc06ac2964e5551b23",
          "md5": "aa12001469d157b17af143901162a628"
        }
      ]
    }
  ]
}
