{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.network_info",
    "module": "network_info_plus",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus-1.1.0-debug.aar",
          "url": "network_info_plus-1.1.0-debug.aar",
          "size": 12124,
          "sha512": "79349856e1b1210ac258a0f57684a4d2fb67fb41988b87ec7f9186a1745c7ea2fb77948c5ca9e43c466d81fe0b05a8932c27655ed4082e41b4198368f27e450c",
          "sha256": "a21dc773a1aa361c1833d9ba633ed40d625d5f25d988cf31215f33db49434353",
          "sha1": "910b35ef47e5cb4bff7fd7a1a07f92b8f3a8e537",
          "md5": "9dad39440b25a83dd49dc76b2a777132"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus-1.1.0-debug.aar",
          "url": "network_info_plus-1.1.0-debug.aar",
          "size": 12124,
          "sha512": "79349856e1b1210ac258a0f57684a4d2fb67fb41988b87ec7f9186a1745c7ea2fb77948c5ca9e43c466d81fe0b05a8932c27655ed4082e41b4198368f27e450c",
          "sha256": "a21dc773a1aa361c1833d9ba633ed40d625d5f25d988cf31215f33db49434353",
          "sha1": "910b35ef47e5cb4bff7fd7a1a07f92b8f3a8e537",
          "md5": "9dad39440b25a83dd49dc76b2a777132"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus-1.1.0-release.aar",
          "url": "network_info_plus-1.1.0-release.aar",
          "size": 11696,
          "sha512": "93dc630774abcb88b9e5b90c5a2084581623750da08a39caa0d4f9adac989a7be269235fcc35e3f833338173646a53996da4622d52c89988249dec29fb7b49e9",
          "sha256": "b48e585f6ea9d483eaa403c3f1ac2c7426816d40b6fa417c3ee96ce8d9514bd8",
          "sha1": "ef27624888e259b54356d999f4d83b8894569b7e",
          "md5": "1d87395c6a6ab862577a2c0c9e1da45f"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus-1.1.0-release.aar",
          "url": "network_info_plus-1.1.0-release.aar",
          "size": 11696,
          "sha512": "93dc630774abcb88b9e5b90c5a2084581623750da08a39caa0d4f9adac989a7be269235fcc35e3f833338173646a53996da4622d52c89988249dec29fb7b49e9",
          "sha256": "b48e585f6ea9d483eaa403c3f1ac2c7426816d40b6fa417c3ee96ce8d9514bd8",
          "sha1": "ef27624888e259b54356d999f4d83b8894569b7e",
          "md5": "1d87395c6a6ab862577a2c0c9e1da45f"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus-1.1.0-profile.aar",
          "url": "network_info_plus-1.1.0-profile.aar",
          "size": 11700,
          "sha512": "7a7250bf5e549eea324ecd19db789f7dfa16f8a14d77999c0da2b40c984346cb837591256a1386b1be3738f242901f424aaa0646916434e7e926549b2a6fda1c",
          "sha256": "8c967d323c0e8be89ef4e7684bb2cd1a36ebd646a0ecbb0977824b8a8b5c5e50",
          "sha1": "7e0c834080ffa74d3cc94edc06ac2964e5551b23",
          "md5": "aa12001469d157b17af143901162a628"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus-1.1.0-profile.aar",
          "url": "network_info_plus-1.1.0-profile.aar",
          "size": 11700,
          "sha512": "7a7250bf5e549eea324ecd19db789f7dfa16f8a14d77999c0da2b40c984346cb837591256a1386b1be3738f242901f424aaa0646916434e7e926549b2a6fda1c",
          "sha256": "8c967d323c0e8be89ef4e7684bb2cd1a36ebd646a0ecbb0977824b8a8b5c5e50",
          "sha1": "7e0c834080ffa74d3cc94edc06ac2964e5551b23",
          "md5": "aa12001469d157b17af143901162a628"
        }
      ]
    }
  ]
}
