{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.1.0.aar",
          "url": "webview_flutter_android_release-1.1.0.aar",
          "size": 107413,
          "sha512": "e6ad76ae2d860c446f3eea62292cb34ed48a707d6eb5b4bbb78cd13bb7de3ba91fb8a366101e75b41f95b26d3eb5abe40b8ce476695101e356e363ced568e461",
          "sha256": "edaf04b9d700638d0d06134fdb3d69cd1a657f58d2e86ebf537d7624a8348933",
          "sha1": "182dfd956ec9383c979e0f98db5838088bf75e39",
          "md5": "884b1ab03ccfafac409f491184084ca9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.1.0.aar",
          "url": "webview_flutter_android_release-1.1.0.aar",
          "size": 107413,
          "sha512": "e6ad76ae2d860c446f3eea62292cb34ed48a707d6eb5b4bbb78cd13bb7de3ba91fb8a366101e75b41f95b26d3eb5abe40b8ce476695101e356e363ced568e461",
          "sha256": "edaf04b9d700638d0d06134fdb3d69cd1a657f58d2e86ebf537d7624a8348933",
          "sha1": "182dfd956ec9383c979e0f98db5838088bf75e39",
          "md5": "884b1ab03ccfafac409f491184084ca9"
        }
      ]
    }
  ]
}
