{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.network_info",
    "module": "network_info_plus_release",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus_release-1.1.1.aar",
          "url": "network_info_plus_release-1.1.1.aar",
          "size": 11696,
          "sha512": "93dc630774abcb88b9e5b90c5a2084581623750da08a39caa0d4f9adac989a7be269235fcc35e3f833338173646a53996da4622d52c89988249dec29fb7b49e9",
          "sha256": "b48e585f6ea9d483eaa403c3f1ac2c7426816d40b6fa417c3ee96ce8d9514bd8",
          "sha1": "ef27624888e259b54356d999f4d83b8894569b7e",
          "md5": "1d87395c6a6ab862577a2c0c9e1da45f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "network_info_plus_release-1.1.1.aar",
          "url": "network_info_plus_release-1.1.1.aar",
          "size": 11696,
          "sha512": "93dc630774abcb88b9e5b90c5a2084581623750da08a39caa0d4f9adac989a7be269235fcc35e3f833338173646a53996da4622d52c89988249dec29fb7b49e9",
          "sha256": "b48e585f6ea9d483eaa403c3f1ac2c7426816d40b6fa417c3ee96ce8d9514bd8",
          "sha1": "ef27624888e259b54356d999f4d83b8894569b7e",
          "md5": "1d87395c6a6ab862577a2c0c9e1da45f"
        }
      ]
    }
  ]
}
