{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_file_release",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_release-1.1.1.aar",
          "url": "open_file_release-1.1.1.aar",
          "size": 13292,
          "sha512": "c44bf9125bba14804a6befb93126ecc3452cc1de3e214cf0f67b8990a137f179b24e31c891ab0e7a51ffec7adddab5be27a3117eddef69413ad7e3d7c892c603",
          "sha256": "43ff5e68774f4c912264d6ee8d247e24d10238c1d504913c19f0fbedf0b3311a",
          "sha1": "1d1071ec62a930b7471918a2b5ee2ab0fc7796d1",
          "md5": "07421763b2bd2b423fba04f62fbccf12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_release-1.1.1.aar",
          "url": "open_file_release-1.1.1.aar",
          "size": 13292,
          "sha512": "c44bf9125bba14804a6befb93126ecc3452cc1de3e214cf0f67b8990a137f179b24e31c891ab0e7a51ffec7adddab5be27a3117eddef69413ad7e3d7c892c603",
          "sha256": "43ff5e68774f4c912264d6ee8d247e24d10238c1d504913c19f0fbedf0b3311a",
          "sha1": "1d1071ec62a930b7471918a2b5ee2ab0fc7796d1",
          "md5": "07421763b2bd2b423fba04f62fbccf12"
        }
      ]
    }
  ]
}
