{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_profile",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.1.3.aar",
          "url": "webview_flutter_android_profile-1.1.3.aar",
          "size": 107415,
          "sha512": "3bd8290e0869418c29026a50bf7215633c892cde81e5aef40b0522c7cf9b4ab11df24197234c4d0b4f7bd6acdc932f78a18d487ceed575c89b715006a9122d11",
          "sha256": "a8fdf969f71349156a70f39975a12d95ab155a43df8ac90832b4a88e6d23a275",
          "sha1": "1e0616071ecf26223c942bcb78927665f3231cc5",
          "md5": "e272938174caa65ffda02cbf0c1df903"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.1.3.aar",
          "url": "webview_flutter_android_profile-1.1.3.aar",
          "size": 107415,
          "sha512": "3bd8290e0869418c29026a50bf7215633c892cde81e5aef40b0522c7cf9b4ab11df24197234c4d0b4f7bd6acdc932f78a18d487ceed575c89b715006a9122d11",
          "sha256": "a8fdf969f71349156a70f39975a12d95ab155a43df8ac90832b4a88e6d23a275",
          "sha1": "1e0616071ecf26223c942bcb78927665f3231cc5",
          "md5": "e272938174caa65ffda02cbf0c1df903"
        }
      ]
    }
  ]
}
