{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_plus",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.1.2-debug.aar",
          "url": "package_info_plus-1.1.2-debug.aar",
          "size": 7908,
          "sha512": "a6d8ff0053983ca02a868c86b4e4f6877c920863793d78e2597d6ba665d0d1faf474de381367b7a31d337a0c45efbe11185f7e6f8353f474f60058513239174a",
          "sha256": "4235529a0a8df4b45a1028818b96d8d534e27ff4c14084222a500ee7b6f7e82c",
          "sha1": "60bb372fbd9abde4f9695ae9e6acae6e046e1ec0",
          "md5": "49d934cb1ef3753729cc6eae1b71ad86"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.1.2-debug.aar",
          "url": "package_info_plus-1.1.2-debug.aar",
          "size": 7908,
          "sha512": "a6d8ff0053983ca02a868c86b4e4f6877c920863793d78e2597d6ba665d0d1faf474de381367b7a31d337a0c45efbe11185f7e6f8353f474f60058513239174a",
          "sha256": "4235529a0a8df4b45a1028818b96d8d534e27ff4c14084222a500ee7b6f7e82c",
          "sha1": "60bb372fbd9abde4f9695ae9e6acae6e046e1ec0",
          "md5": "49d934cb1ef3753729cc6eae1b71ad86"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.1.2-release.aar",
          "url": "package_info_plus-1.1.2-release.aar",
          "size": 7611,
          "sha512": "83b8bff71925567cc4f35afdf2c5b186ba7bf90489a879dccf83e961e7ced6a4b9e6bbc256d182d6a2ff01b6168a1ca9da904e637f1ccee0ede5413d221153ac",
          "sha256": "88a31bbf1bfa83d32fbe3fb8b6c102a00c7bec7e170f33674bd79616075e98ab",
          "sha1": "fb58115af0b69a9c7653a46830db80870a60e2d7",
          "md5": "c39d8299b0025d9a13fc592bf045d153"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.1.2-release.aar",
          "url": "package_info_plus-1.1.2-release.aar",
          "size": 7611,
          "sha512": "83b8bff71925567cc4f35afdf2c5b186ba7bf90489a879dccf83e961e7ced6a4b9e6bbc256d182d6a2ff01b6168a1ca9da904e637f1ccee0ede5413d221153ac",
          "sha256": "88a31bbf1bfa83d32fbe3fb8b6c102a00c7bec7e170f33674bd79616075e98ab",
          "sha1": "fb58115af0b69a9c7653a46830db80870a60e2d7",
          "md5": "c39d8299b0025d9a13fc592bf045d153"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.1.2-profile.aar",
          "url": "package_info_plus-1.1.2-profile.aar",
          "size": 7610,
          "sha512": "aecd1b5622dd360cda8b6ba22599b1c14d60fad2db946fd9bd39aca6477e5f2686af92e13b43ed884850a31537358a161c173fe0202c78be1dcbcd37714c2f7c",
          "sha256": "448339ce9b6e54ec25d454b59952219c62b3b2f4a98d2d51b693b46b439fb66f",
          "sha1": "71ffb54b99ba7841dd01d03599767b2d5b25c2dd",
          "md5": "c9bf8711181237599fed8a61e2f25078"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus-1.1.2-profile.aar",
          "url": "package_info_plus-1.1.2-profile.aar",
          "size": 7610,
          "sha512": "aecd1b5622dd360cda8b6ba22599b1c14d60fad2db946fd9bd39aca6477e5f2686af92e13b43ed884850a31537358a161c173fe0202c78be1dcbcd37714c2f7c",
          "sha256": "448339ce9b6e54ec25d454b59952219c62b3b2f4a98d2d51b693b46b439fb66f",
          "sha1": "71ffb54b99ba7841dd01d03599767b2d5b25c2dd",
          "md5": "c9bf8711181237599fed8a61e2f25078"
        }
      ]
    }
  ]
}
